### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by Chwiggy** [MichaelsJP/gtfs-general#10]
Following the install instructions from the readme doesn't work correctly.

After running `python -m gtfs-general --help` python returns the error `No module named gtfs-general`.

The poetry install process seems to be broken as well. Trying to run the file with `poetry run gtfs-general --help` can at least locate the gtfs-general module, which then throws the error `ModuleNotFoundError: No module named 'fastapi'`. And fastapi seems not installed in the virtual environment that poetry was supposed to set up

Running the files in the vscode and vscodium debugger and manually installing dependencies seems to brake at a local import in src/gtfs-general/logging.py line 4.

Tested on debian 12 and nixos 23.11 with python 3.11 and fresh installs of poetry.

**Comment by MichaelsJP** [comment]
@Chwiggy Thanks for reporting. It would be cool if you could have a quick look at master and the updated readme to see if your error is gone now.

**Comment by Chwiggy** [comment]
sorry for the late reply, but yes now the setup works with no issues!
